@echo off
echo Starting AnmaAI Desktop Application...
echo.
echo Starting server...
start /b cmd /c "npm run dev"
echo Waiting for server to initialize...
timeout /t 5 /nobreak > nul
echo Starting desktop app...
npx electron .
echo.
echo Desktop application closed.
pause